name: test-chatgpt-code-reviewer
run-name: test-chatgpt-code-reviewer
on: [pull_request]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  chatgpt-code-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: ChatGPT Review
        uses: abdullahessam/chatgpt-code-reviewer@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # CUSTOM_PROMPT: ${{ secrets.CUSTOM_PROMPT }}  # Optional: Custom prompt for code reviews
